### ISSUE TITLE
Unexpected Token: {

### ISSUE THREAD

**Issue by lukeed** [infernojs/babel-plugin-inferno#29]
Cannot attach version `1.2.0-beta11` to Babel. As soon as I do, the following stack is thrown:

```
ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at ~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:174:20
    at Array.map (native)
    at Function.normalisePlugins (~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (~/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (~/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (~/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (~/node_modules/babel-loader/lib/index.js:41:20)
    at Object.module.exports (~/node_modules/babel-loader/lib/index.js:138:12)
```

It's nothing to do with my source file: `src/index.js`. To verify, I set its contents to:

```js
console.log('nearly empty');
```

and the error is still thrown.

Reverting to `1.0.0-legacy` allowed me to continue working.

**Comment by trueadm** [comment]
@lukeed `beta11`+ required Node 6+, given Node 6 is now LTS, we moved to it as min version.

**Comment by lukeed** [comment]
Ah, missed that. Where's the breaking change in this case?

I wonder because 4.5 is still LTS until Apr 2017

**Comment by trueadm** [comment]
@lukeed Given that the plugin is still in beta, we didn't officially announce this yet (was going to when officially released). We wanted to move forward with 6, due to the ease of maintaining an easier codebase using ES2016. It should be possible to compile the plugin to ES5 for people on Node 4. Is it possible for you to use Node 6 until this happens?

**Comment by lukeed** [comment]
Yes, I can also "convert" it for 4.6

The majority of ES2015 runs on Node 4.6. Having only briefly run thru Inferno source, the only unsupported feature that comes to mind is spread operator.

Out of the house right now, so can't dig thru this repo for any potential issues, but I doubt there are any.

**Comment by lukeed** [comment]
Using Inferno source as reference because I've seen that you like to use spreads. I'm only assuming that spreads are used here too.

Obviously the node version won't affect inferno and its compiled output.

**Comment by trueadm** [comment]
@lukeed yep, it's pretty much spreads that need to be compiled. Inferno itself is always compiled into single bundles
