### ISSUE TITLE
Babel 7 issue transpiling JSX for custom components

### ISSUE THREAD

**Issue by insin** [infernojs/babel-plugin-inferno#46]
In the process of [upgrading nwb to Babel 7 beta](https://github.com/insin/nwb/issues/403) I've found a weird issue with using JSX in an app's entry module.

This is my entry module...

```js
import './index.css'

import Inferno from 'inferno'

import App from './App'

Inferno.render(<App/>, document.querySelector('#app'))

if (module.hot) {
  module.hot.accept()
}
```

...which gives me the following error after upgrading to Babel 7.0.0-beta.37, using babel-plugin-inferno 3.3.1:

```
Module build failed: TypeError: Property arguments[1] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName"] but instead got "JSXIdentifier"
    at validate (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\definitions\utils.js:136:13)
    at validator (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\definitions\utils.js:95:7)
    at Object.validate (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\definitions\utils.js:191:10)
    at validate (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\validators\validate.js:15:9)
    at builder (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\builders\builder.js:40:27)
    at Object.CallExpression (C:\Users\Jonny\repos\nwb\node_modules\@babel\types\lib\builders\generated\index.js:276:27)
    at createVNode (C:\Users\Jonny\repos\nwb\node_modules\babel-plugin-inferno\lib\index.js:385:12)
    at PluginPass.enter (C:\Users\Jonny\repos\nwb\node_modules\babel-plugin-inferno\lib\index.js:428:17)
    at newFn (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\visitors.js:223:21)
    at NodePath._call (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\path\context.js:64:19)
    at NodePath.call (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\path\context.js:38:17)
    at NodePath.visit (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\path\context.js:99:12)
    at TraversalContext.visitQueue (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\context.js:139:18)
    at TraversalContext.visitMultiple (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\context.js:93:17)
    at TraversalContext.visit (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\context.js:178:19)
    at Function.traverse.node (C:\Users\Jonny\repos\nwb\node_modules\@babel\traverse\lib\index.js:76:17)
```

Whereas if I avoid using JSX, it works correctly:

```js
Inferno.render(Inferno.createVNode(1 << 4, App), document.querySelector('#app'))
```

**Comment by insin** [comment]
It looks like this may be related to https://github.com/babel/babel/issues/6851, after which a `JSXIdentifier` is no longer an `Expression`

**Comment by insin** [comment]
This change to `getVNodeType(t, type)` seems to fix it, returning an Identifier with the JSXIdentifier's name instead of the JSXIdentifier itself - I assume this should work for all versions of Babel?

```diff
  if (astType === 'JSXIdentifier') {
    if (isComponent(type.name)) {
      component = true;
+     type = t.identifier(type.name);
      flags = VNodeFlags.ComponentUnknown;
    } else {
```

**Comment by Havunen** [comment]
It would be helpful if you could test that it works on babel6 and sent PR for it. We would also need same fix for v4-beta branch.
